version: "3"  # Specify the version of Docker Compose being used

services:  # Define the services that make up the application

  application:  # Define the application service
    restart: unless-stopped  # Specify the restart policy for the container
    expose:
      - 3000  # Expose port 3000 from the container
    build:  # Specify how to build the container
      context: .  # Use the current directory as the build context
    environment:  # Set environment variables for the container
      - NUXT_SECRET=${NUXT_SECRET}
      - ORIGIN=${ORIGIN}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

  reverse-proxy:  # Define the reverse-proxy service
    restart: unless-stopped  # Specify the restart policy for the container
    image: staticfloat/nginx-certbot  # Use the staticfloat/nginx-certbot image as the base image for the container
    ports:
      - 80:80/tcp  # Expose port 80 on the host and forward it to port 80 in the container
      - 443:443/tcp  # Expose port 443 on the host and forward it to port 443 in the container
    environment:  # Set environment variables for the container
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - ENVSUBST_VARS=CERTBOT_DOMAIN
    volumes:  # Mount volumes in the container
      - letsencrypt:/etc/letsencrypt  # Mount the 'letsencrypt' volume to '/etc/letsencrypt' in the container
      - ./nginx.conf:/etc/nginx/user.conf.d/nginx.conf:ro  # Mount the 'nginx.conf' file as read-only to '/etc/nginx/user.conf.d/nginx.conf' in the container
    depends_on:
      - application  # Specify that the reverse-proxy service depends on the application service

volumes:  # Define volumes that can be used by the services
    letsencrypt:  # Define the 'letsencrypt' volume
